
baseURL = "http://atf.jace.pro/"
languageCode = "en-us"
title = "ATF"
theme = "hugograyscale"
#googleAnalytics = ""
[params]
    # Provide some metadata for search and indexing services
    description = "Automated Testing Framework tests that SHOULD have been"
    author = "Jace Benson"